### ISSUE TITLE
coreaudiod high CPU usage 

### ISSUE THREAD

**Issue by thomasjpr** [The9Labs/AudioMate#14]
I'm seeing issue similar to (https://github.com/TroikaLabs/AudioMate/issues/12) in version 2.1.4. As soon as I open AudioMate, coreaudiod is racing out of control.

**Comment by sonicbee9** [comment]
@thomasjpr Could you provide some more details? OS X version, audio devices connected, etc.

**Comment by RickCogley** [comment]
@rnine hi, with AudioMate 2.2.3 running on Yosemite 10.10.3 on a new Macbook Pro purchased Jun 12, 2015, in an idling state (no sound of any kind being generated, no headphones connected) I'm seeing: 

* coreaudiod cpu 50%+
* AudioMate cpu 15%+, energy impact 15%+

Hope this helps.

**Comment by rnine** [comment]
@RickCogley Hi Rick. Thanks for your report.

It is interesting to see that some people are being affected by this problem while others are not. In my environment I have tried combining Firewire, USB, virtual audio devices, and even aggregate and multi-output devices, but the CPU load remains at 0-1%.

Do you have any external (USB, Firewire, Thunderbolt, or Bluetooth) audio devices connected? Any virtual audio drivers (AirParrot, Boom, SoundFlower, etc.)? In other words, are there any other audio devices present in your system other than the standard MBP in and out?

**Comment by tluck** [comment]
just built and installed on my MBP8,1. I am seeing the same thing. high cpu for coreaudiod when it must display something on menu bar. when the menu bar displays sample rate and volume coreaudiod goes  nuts.  but if i turn off that menu bar display (so just see icon), then i just see audioMate taking 25%. i am running 10.11.2

**Comment by rnine** [comment]
Should be addressed in https://github.com/The9Labs/AudioMate/commit/525e81d89dbd22090938fb07ead88c95aa0ad7b0. 

See discussion on #19

**Comment by RickCogley** [comment]
@rnine sorry to not answer your entry above. I totally missed it. I always have an external monitor connected at home and at work, so I suspect this was related to that. Perhaps because external monitors _can_ have sound output via thunderbolt, os x somehow treats them like they _do_ even when they don't. Wild speculation, but...
