### ISSUE TITLE
high CPU with Dual Monitors

### ISSUE THREAD

**Issue by tluck** [The9Labs/AudioMate#19]
just built and installed v2.2.3 on my MBP8,1. I am seeing the same thing that others reported. high cpu for coreaudiod when it must display something on menu bar. when the menu bar displays sample rate and volume coreaudiod goes nuts. but if i turn off that menu bar display (so just see icon), then i just see audioMate taking 25%.

the overall problem shows up ONLY i have dual monitors - meaning with just 1 display there is no extra CPU cycles for audioMate or coreaudiod.

**Comment by rnine** [comment]
@tluck Thanks for reporting. Do these monitors provide additional audio outputs to your system when connected?

**Comment by tluck** [comment]
no. the external monitor is pure display. i suspect its an issue with the way the menu bar is works on dual monitors. if close the LCD and use the external monitory, these runaway processes behave just the laptop with just LCD. i.e. LCD + external display = problem.

**Comment by rnine** [comment]
@tluck Gotcha! That was really helpful. Finally I was able to reproduce this issue using 2 external displays :+1: 

I'll investigate a bit further and report back.

**Comment by rnine** [comment]
@tluck I think I was able to address this issue in https://github.com/The9Labs/AudioMate/commit/525e81d89dbd22090938fb07ead88c95aa0ad7b0. 

I have tagged version v2.2.4-beta1 and attached a dmg that you can download at https://github.com/The9Labs/AudioMate/releases/tag/v2.2.4-beta1 — please let me know if it fixes the issue you were experiencing :)

**Comment by tluck** [comment]
works! with LCD + External there are no run-away or high cpu items as before. great.

**Comment by rnine** [comment]
@tluck Great, glad to hear it worked! :+1: 

I'll do some further testing on another setup and then prepare v2.2.4 for release if everything looks good.

**Comment by RickCogley** [comment]
@rnine thanks, I confirm low cpu on mine, too, and that I always use an external monitor. What a nice catch. :-)
