### ISSUE TITLE
Keyboard controls to control input level?

### ISSUE THREAD

**Issue by karlbecker** [The9Labs/AudioMate#20]
Hello,
I would love to have keyboard controls to control the input level in real time.  Do you know of any feature that already exists for Mac OS X, or in AudioMate, that allows this?

If not, maybe I'll need to make a (probably not trivial) code contribution!

Thanks!

**Comment by rnine** [comment]
@karlbecker Hello. Not currently supported, but this feature will be included in v3 — please check #18

If you would like to contribute to #18, it would be better to wait until I push v3 branch (Swift 2.x rewrite + new UI) in a week or two :+1:

**Comment by karlbecker** [comment]
Thanks! I'm happy to give a code review if you're already working on it, although I've done pretty much no Swift yet. It'll be a good learning experience!
